=== bathole/Projet-XML-Version-Finale/Royal.dtd
<!ELEMENT ROYAL (HEAD | SUBM | INDI | FAM)*>
<!-- HEAD -->
<!ELEMENT HEAD (FILE?, CHAR?,SOUR?,DATE?,DEST?)*>
<!ELEMENT FILE (#PCDATA)>
<!ELEMENT CHAR (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT SOUR (#PCDATA)>
<!ELEMENT DEST (#PCDATA)>
<!-- SUBM -->
<!ELEMENT SUBM (NAME, ADDR,PHON,COMM)?>
<!ATTLIST SUBM id ID #REQUIRED>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT ADDR (#PCDATA|CONT)*>
<!ELEMENT CONT (#PCDATA)>
<!ELEMENT PHON (#PCDATA)>
<!ELEMENT COMM (#PCDATA|CONT)*>

<!-- INDI -->
<!ELEMENT INDI (NAME?| TITL?| SEX?| BIRT?| CHR?| DEAT?| BURI?| REFN?| (FAMS*)?| FAMC?| OBJE?)*>
<!ATTLIST INDI id ID #REQUIRED>
<!ELEMENT TITL (#PCDATA)>
<!ELEMENT SEX (#PCDATA)>

<!-- BIRTH -->
<!ELEMENT BIRT (DATE?,PLAC?)>
<!ELEMENT PLAC (#PCDATA)>

<!-- CHR -->
<!ELEMENT CHR (DATE?, PLAC?)>

<!-- DEATH -->
<!ELEMENT DEAT (DATE?, PLAC?)>

<!-- BURI -->
<!ELEMENT BURI (DATE?, PLAC?)>

<!-- REFN -->
<!ELEMENT REFN (#PCDATA)>

<!ELEMENT FAMS EMPTY>
<!ATTLIST FAMS id IDREF #REQUIRED>
<!ELEMENT FAMC EMPTY>
<!ATTLIST FAMC id IDREF #REQUIRED>


<!--  FAM -->
<!ELEMENT FAM (HUSB?, WIFE?, (CHIL*)?, DIV?, MARR?, OBJE?)>
<!ATTLIST FAM id ID #REQUIRED>
<!ELEMENT HUSB EMPTY>
<!ATTLIST HUSB id IDREF #REQUIRED>
<!ELEMENT WIFE EMPTY>
<!ATTLIST WIFE id IDREF #REQUIRED>
<!ELEMENT CHIL EMPTY>
<!ATTLIST CHIL id IDREF #REQUIRED>
<!ELEMENT DIV (#PCDATA)>
<!ELEMENT MARR (DATE?, PLAC?)>

=== bathole/Projet-XML-Version-Finale/doe.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE ROYAL SYSTEM "Royal.dtd">
<ROYAL>
<HEAD>
<SOUR>FTW</SOUR>
<DEST>PAF</DEST>
<DATE>10 APR 1999 </DATE>
<CHAR>ANSI</CHAR>
<FILE>doe.ged</FILE>
</HEAD>
<INDI id="I01">
<NAME>John /Doe/ </NAME>
<SEX>M</SEX>
<BIRT>
<DATE>23 JAN 1961 </DATE>
<PLAC>Australia</PLAC>
</BIRT>
<DEAT>
<DATE>8 JUL 1988 </DATE>
<PLAC>Scotland</PLAC>
</DEAT>
<FAMS id="F1"/>
</INDI>
<INDI id="I02">
<NAME>Rosanna /Housewife/ </NAME>
<SEX>F</SEX>
<BIRT>
<DATE>15 DEC 1968 </DATE>
<PLAC>Canada</PLAC>
</BIRT>
<DEAT>
<DATE>8 JUL 1988 </DATE>
<PLAC>Scotland</PLAC>
</DEAT>
<FAMS id="F1"/>
</INDI>
<INDI id="I03">
<NAME>Joe /Doe/ </NAME>
<SEX>M</SEX>
<BIRT>
<DATE>15 JUN 1988 </DATE>
<PLAC>United States </PLAC>
</BIRT>
<DEAT>
<DATE>8 JUL 1988 </DATE>
<PLAC>Scotland</PLAC>
</DEAT>
<FAMC id="F1"/>
</INDI>
<FAM id="F1">
<HUSB id="I01"/>
<WIFE id="I02"/>
<CHIL id="I03"/>
<MARR>
<DATE>7 AUG 1987 </DATE>
<PLAC>United States </PLAC>
</MARR>
</FAM>
</ROYAL>

=== bathole/Projet-XML-Version-Finale/complet.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE ROYAL SYSTEM "Royal.dtd">
<ROYAL>
<HEAD/>
<FAM id="F1">
<HUSB id="I1"/>
<WIFE id="I2"/>
<CHIL id="I3"/>
<CHIL id="I4"/>
<MARR>
<DATE>7 AUG 1987 </DATE>
<PLAC>United States </PLAC>
</MARR>
</FAM>
<FAM id="F2">
<HUSB id="I3"/>
<WIFE id="I5"/>
<CHIL id="I7"/>
<CHIL id="I9"/>
<MARR>
<DATE>7 APR 1997 </DATE>
<PLAC>France</PLAC>
</MARR>
</FAM>
<FAM id="F3">
<HUSB id="I6"/>
<WIFE id="I4"/>
<CHIL id="I17"/>
<CHIL id="I11"/>
<CHIL id="I12"/>
<CHIL id="I13"/>
<MARR>
<DATE>13 JUN 2001 </DATE>
<PLAC>Italie</PLAC>
</MARR>
</FAM>
<FAM id="F4">
<HUSB id="I7"/>
<WIFE id="I8"/>
<CHIL id="I14"/>
<CHIL id="I15"/>
</FAM>
<FAM id="F5">
<HUSB id="I9"/>
<WIFE id="I10"/>
<CHIL id="I16"/>
</FAM>
<INDI id="I1">
<NAME>J»rŸme /Turing/ </NAME>
<SEX>M</SEX>
<FAMS id="F1"/>
</INDI>
<INDI id="I2">
<NAME>Estelle /Knuth/ </NAME>
<SEX>F</SEX>
<FAMS id="F1"/>
</INDI>
<INDI id="I3">
<NAME>Frederic /Turing/ </NAME>
<SEX>M</SEX>
<FAMC id="F1"/>
<FAMS id="F2"/>
</INDI>
<INDI id="I5">
<NAME>Caroline /Rabin/ </NAME>
<SEX>F</SEX>
<FAMS id="F2"/>
</INDI>
<INDI id="I4">
<NAME>Julie /Turing/ </NAME>
<SEX>F</SEX>
<FAMC id="F1"/>
<FAMS id="F3"/>
</INDI>
<INDI id="I6">
<NAME>Nicolas /B∏chi/ </NAME>
<SEX>M</SEX>
<FAMS id="F3"/>
</INDI>
<INDI id="I7">
<NAME>Arnaud /Turing/ </NAME>
<SEX>M</SEX>
<FAMC id="F2"/>
<FAMS id="F4"/>
</INDI>
<INDI id="I8">
<NAME>Laurence /Church/ </NAME>
<SEX>F</SEX>
<FAMS id="F4"/>
</INDI>
<INDI id="I9">
<NAME>Manuel /Turing/ </NAME>
<SEX>M</SEX>
<FAMC id="F2"/>
<FAMS id="F5"/>
</INDI>
<INDI id="I10">
<NAME>Nicole /von Neumann/ </NAME>
<SEX>F</SEX>
<FAMS id="F5"/>
</INDI>
<INDI id="I11">
<NAME>Dylan /B∏chi/ </NAME>
<SEX>M</SEX>
<FAMC id="F3"/>
</INDI>
<INDI id="I12">
<NAME>S»verine /B∏chi/ </NAME>
<SEX>F</SEX>
<FAMC id="F3"/>
</INDI>
<INDI id="I13">
<NAME>Martine /B∏chi/ </NAME>
<SEX>F</SEX>
<FAMC id="F3"/>
</INDI>
<INDI id="I17">
<NAME>Sylvain /B∏chi/ </NAME>
<SEX>M</SEX>
<FAMC id="F3"/>
</INDI>
<INDI id="I14">
<NAME>Fran¡oise /Turing/ </NAME>
<SEX>F</SEX>
<FAMC id="F4"/>
</INDI>
<INDI id="I15">
<NAME>David /Turing/ </NAME>
<SEX>M</SEX>
<FAMC id="F4"/>
</INDI>
<INDI id="I16">
<NAME>Alan /Turing/ </NAME>
<SEX>M</SEX>
<FAMC id="F5"/>
</INDI>
</ROYAL>

=== bathole/Projet-XML-Version-Finale/begood.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE ROYAL SYSTEM "Royal.dtd">
<ROYAL>
<HEAD/>
<INDI id="I1">
<NAME>John /Begood/ </NAME>
<SEX>M</SEX>
<FAMS id="F1"/>
</INDI>
<INDI id="I2">
<NAME>Ada /Begood/ </NAME>
<FAMS id="F1"/>
</INDI>
<INDI id="I3">
<NAME>Fred /Begood/ </NAME>
<FAMC id="F1"/>
</INDI>
<INDI id="I4">
<NAME>Lea /Begood/ </NAME>
<SEX>F</SEX>
<FAMC id="F1"/>
</INDI>
<FAM id="F1">
<HUSB id="I1"/>
<WIFE id="I2"/>
<CHIL id="I3"/>
<CHIL id="I4"/>
</FAM>
</ROYAL>
